# Generated by Django 5.2.4 on 2025-10-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeisenbergSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.JSONField(help_text='The signature as a 3x1 matrix.')),
                ('private_key', models.JSONField(help_text='The private key (3x3 matrix).')),
                ('field_prime', models.PositiveIntegerField(help_text='The prime field size used in the Heisenberg group.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the signature was created.')),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to='app.uploadedfile')),
            ],
        ),
    ]
