# Generated by Django 5.2.4 on 2025-10-24 12:01

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_heisenbergsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_matrix', app.models.ArrayField()),
                ('private_key_matrix', app.models.ArrayField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to='app.uploadedfile')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
        migrations.DeleteModel(
            name='HeisenbergSignature',
        ),
    ]
